select *
--w.ZZCREATEDATE, a.*
--ASSETNUM, LOCATION, DESCRIPTION, INSTALLDATE, SITEID, STATE, ZZTYPE 
--from workorder w, asset a
from asset a
--, ASSETSPEC
WHERE (
    a.DESCRIPTION LIKE 'EXTERIOR COMPACTOR%'
    OR (
        (a.DESCRIPTION = 'INT./EXTERIOR COMPACTOR' 
        OR a.DESCRIPTION = 'INT./ EXTERIOR COMPACTOR')
        AND LENGTH(a.DESCRIPTION) = 3)
    ) 
AND a.LOCATION LIKE '123%'
--AND a.STATUS = 'OPERATING'  
--AND a.assetnum = w.assetnum
ORDER BY w.ZZCREATEDATE DESC