select WONUM, PARENT_TDS_NUM, TDS_NUM, PARENT, WORKTYPE, LOCATION, DISPOSITION_SUB_CODE, STATUS, DEL_ASS_DATE_SOURCE, DEL_COMPLETE_DATE_TIME, OWNERGROUP, ZZCREATE_DAY_ID, REPORT_DAY_ID, ACTSTART, ACTFINISH, STATUS_DAY_ID, ZZSUBWORKTYPE
from eisdw.wts_task_fact
where failurecode = 'HEATOUTAGE'
and ZZSUBWORKTYPE <> 'PLANNED'
and ZZCREATE_DAY_ID >= '20170101'